hsaasooxoooe000000e-------qqqqqqqqqqq
ddddddddddddddddddiiiivvvvvvvvvvvvvvv
pppppppppeeeeeeeeeeettttttttttttttttttt
eeeeeeeeeeeeeeeeuuuuuuuuuuuuooooooooooo
yyyyyyyyyyyyyyyyiiiiiiiiiippppppppppppp
bbbbbbbbbbbbbbyyyyyyyyyyrrrrrrrrrrrrrrr
